services:

  breezewiki:
    container_name: breezewiki
    image: quay.io/pussthecatorg/breezewiki:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:10416:10416" # Replace with "10416:10416" if you don't use a reverse proxy
    volumes:
      - "./config.ini:/app/config.ini"